name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Yanushanth-Rv
          outputs: |
            dist/github-contribution-grid-snake.svg
      
      - name: Upload Snake to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: snake-artifact
          path: dist/github-contribution-grid-snake.svg
